--Name:         cherry_rainbow

vim.api.nvim_set_hl(0, "VertSplit", {link = "StatusLineNC"}) 
vim.api.nvim_set_hl(0, "StatusLineTerm", {link = "StatusLine"}) 
vim.api.nvim_set_hl(0, "StatusLineTermNC", {link = "StatusLineNC"}) 
--vim.api.nvim_set_hl(0, "TabLineFill", {link = "TabLine"}) 
vim.api.nvim_set_hl(0, "Terminal", {link = "Normal"}) 
vim.api.nvim_set_hl(0, "CursorColumn", {link = "CursorLine"}) 
vim.api.nvim_set_hl(0, "CursorIM", {link = "Cursor"}) 
vim.api.nvim_set_hl(0, "LineNrAbove", {link = "LineNr"}) 
vim.api.nvim_set_hl(0, "LineNrBelow", {link = "LineNr"}) 
vim.api.nvim_set_hl(0, "Debug", {link = "Special"}) 
vim.api.nvim_set_hl(0, "diffAdded", {link = "String"}) 
vim.api.nvim_set_hl(0, "diffRemoved", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "diffOnly", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "diffNoEOL", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "diffIsA", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "diffIdentical", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "diffDiffer", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "diffCommon", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "diffBDiffer", {link = "WarningMsg"}) 
vim.api.nvim_set_hl(0, "lCursor", {link = "Cursor"}) 
vim.api.nvim_set_hl(0, "CurSearch", {link = "Search"}) 
vim.api.nvim_set_hl(0, "CursorLineFold", {link = "CursorLine"}) 
vim.api.nvim_set_hl(0, "CursorLineSign", {link = "CursorLine"}) 
vim.api.nvim_set_hl(0, "Boolean", {link = "Constant"}) 
vim.api.nvim_set_hl(0, "Character", {link = "Constant"}) 
vim.api.nvim_set_hl(0, "Conditional", {link = "Statement"}) 
vim.api.nvim_set_hl(0, "Define", {link = "PreProc"}) 
vim.api.nvim_set_hl(0, "Exception", {link = "Statement"}) 
vim.api.nvim_set_hl(0, "Include", {link = "PreProc"}) 
vim.api.nvim_set_hl(0, "Keyword", {link = "Statement"}) 
vim.api.nvim_set_hl(0, "Label", {link = "Statement"}) 
vim.api.nvim_set_hl(0, "Macro", {link = "PreProc"}) 
vim.api.nvim_set_hl(0, "Operator", {link = "Statement"}) 
vim.api.nvim_set_hl(0, "PreCondit", {link = "PreProc"}) 
vim.api.nvim_set_hl(0, "Repeat", {link = "Statement"}) 
vim.api.nvim_set_hl(0, "SpecialChar", {link = "Special"}) 
vim.api.nvim_set_hl(0, "String", {link = "Constant"}) 
vim.api.nvim_set_hl(0, "MessageWindow", {link = "Pmenu"}) 
vim.api.nvim_set_hl(0, "PopupNotification", {link = "Todo"}) 

vim.api.nvim_set_hl(0, "Structure", {link = "Typedef"}) 
vim.api.nvim_set_hl(0, "Float", {link = "Number"}) 

--Custom:
vim.api.nvim_set_hl(0, "Normal", {fg="none", bg="none"})

vim.api.nvim_set_hl(0, "Constant", {fg="#4EA006", bg="none"})
vim.api.nvim_set_hl(0, "Comment", {fg="#777777", bg="none"})
vim.api.nvim_set_hl(0, "Special", {fg="#4465B4", bg="none"})
vim.api.nvim_set_hl(0, "Statement", {fg="#D35675", bg="none"})
vim.api.nvim_set_hl(0, "Function", {fg="#75507B", bg="none"})
vim.api.nvim_set_hl(0, "Identifier", {fg="#ff80ff", bg="none"})
vim.api.nvim_set_hl(0, "Variable", {fg="#ffffff", bg="none"})
vim.api.nvim_set_hl(0, "Type", {fg="#8D81C2", bg="none"})
vim.api.nvim_set_hl(0, "Typedef", {fg="#4465B4", bg="none"})
vim.api.nvim_set_hl(0, "StorageClass", {fg="#4465B4", bg="none"})
vim.api.nvim_set_hl(0, "Tag", {fg="#4465B4", bg="none"})
vim.api.nvim_set_hl(0, "Delimiter", {fg="#ffa500", bg="none"})
vim.api.nvim_set_hl(0, "SpecialComment", {fg="#00ff00", bg="none"})
vim.api.nvim_set_hl(0, "Number", {fg="#62E0FF", bg="none"})

vim.api.nvim_set_hl(0, "LineNr", {fg="#7A82A3", bg="none"})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg="#ff80ff", bg="#666666"})
vim.api.nvim_set_hl(0, "Error", {fg="#ff0000", bg="#ffffff"})
vim.api.nvim_set_hl(0, "NonText", {fg="#444444", bg="none"})

--Coc, colors
vim.api.nvim_set_hl(0, "CocErrorSign", {fg="#ff0000", bg="none"})
vim.api.nvim_set_hl(0, "CocWarningSign", {fg="#ffff00", bg="none"})
vim.api.nvim_set_hl(0, "CocInfoSign", {fg="#00ff00", bg="none"})
vim.api.nvim_set_hl(0, "CocHintSign", {fg="#62E0FF", bg="none"})

vim.api.nvim_set_hl(0, "ColorColumn", {fg="none", bg="#8b0000"})
vim.api.nvim_set_hl(0, "CursorLine", {fg="none", bg="#666666"})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg="#add8e6", bg="none"})
vim.api.nvim_set_hl(0, "StatusLine", {fg="none", bg="none"})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg="none", bg="none"})
vim.api.nvim_set_hl(0, "TabLineSel", {fg="#333333", bg="#ffffff"})
vim.api.nvim_set_hl(0, "TabLine", {fg="#333333", bg="#d3d3d3"})
vim.api.nvim_set_hl(0, "Pmenu", {fg="#ffffff", bg="#4d4d4d"})
vim.api.nvim_set_hl(0, "PmenuSbar", {fg="none", bg="none", ctermbg="none"})
vim.api.nvim_set_hl(0, "PmenuSel", {fg="#000000", bg="#bebebe"})
vim.api.nvim_set_hl(0, "PmenuThumb", {fg="none", bg="#ffffff"})
vim.api.nvim_set_hl(0, "QuickFixLine", {fg="#ffffff", bg="#8b008b"})
vim.api.nvim_set_hl(0, "Cursor", {fg="#000000", bg="#00ff00"})
vim.api.nvim_set_hl(0, "ErrorMsg", {fg="#ffffff", bg="#ff0000"})
vim.api.nvim_set_hl(0, "Conceal", {fg="none", bg="none",  ctermfg="none", ctermbg="none"})
vim.api.nvim_set_hl(0, "FoldColumn", {fg="#add8e6", bg="none"})
vim.api.nvim_set_hl(0, "Folded", {fg="#00ff00", bg="#000000"})
vim.api.nvim_set_hl(0, "IncSearch", {fg="#00ff00", bg="none"})
vim.api.nvim_set_hl(0, "MatchParen", {fg="none", bg="#008b8b"})
vim.api.nvim_set_hl(0, "ModeMsg", {fg="none", bg="none",  ctermfg="none", ctermbg="none"})
vim.api.nvim_set_hl(0, "MoreMsg", {fg="#2e8b57", bg="none"})
vim.api.nvim_set_hl(0, "Question", {fg="#00ff00", bg="none"})
vim.api.nvim_set_hl(0, "Search", {fg="#000000", bg="#62E0FF"})
vim.api.nvim_set_hl(0, "SignColumn", {fg="#008b8b", bg="none"})
vim.api.nvim_set_hl(0, "SpecialKey", {fg="#00ffff", bg="none"})
vim.api.nvim_set_hl(0, "ToolbarButton", {fg="none", bg="#999999"})
vim.api.nvim_set_hl(0, "ToolbarLine", {fg="none", bg="none",  ctermfg="none", ctermbg="none"})
vim.api.nvim_set_hl(0, "Visual", {fg="#ffff00", bg="#777777"})
vim.api.nvim_set_hl(0, "VisualNOS", {fg="none", bg="none", ctermfg="none", ctermbg="none"})
vim.api.nvim_set_hl(0, "WarningMsg", {fg="#ff0000", bg="none"})
vim.api.nvim_set_hl(0, "WildMenu", {fg="#000000", bg="#ffff00"})
vim.api.nvim_set_hl(0, "debugBreakpoint", {fg="#00008b", bg="#ff0000"})
vim.api.nvim_set_hl(0, "debugPC", {fg="#00008b", bg="#0000ff"})
vim.api.nvim_set_hl(0, "SpellBad", {fg="underline", bg="none", sp="#ff0000"})
vim.api.nvim_set_hl(0, "SpellCap", {fg="#00ff00", bg="none", sp="#00ff00"})
vim.api.nvim_set_hl(0, "SpellLocal", {fg="#00ffff", bg="none", sp="#00ffff"})
vim.api.nvim_set_hl(0, "SpellRare", {fg="#ff80ff", bg="none", sp="#ff80ff"})
vim.api.nvim_set_hl(0, "Directory", {fg="#00ffff", bg="none"})
vim.api.nvim_set_hl(0, "Title", {fg="#ff80ff", bg="none"})
vim.api.nvim_set_hl(0, "Ignore", {fg="#333333", bg="none"})
vim.api.nvim_set_hl(0, "PreProc", {fg="#ff0000", bg="none"})
vim.api.nvim_set_hl(0, "Todo", {fg="#ffff00", bg="#0000ff"})
vim.api.nvim_set_hl(0, "Underlined", {fg="#80a0ff", bg="none"})
vim.api.nvim_set_hl(0, "DiffAdd", {fg="#ffffff", bg="#5f875f"})
vim.api.nvim_set_hl(0, "DiffChange", {fg="#ffffff", bg="#5f87af"})
vim.api.nvim_set_hl(0, "DiffText", {fg="#000000", bg="#c6c6c6"})
vim.api.nvim_set_hl(0, "DiffDelete", {fg="#ffffff", bg="#af5faf"})
